#if !defined(AFX_COMITOGGLESWITCH_H__38806ED6_1788_427F_8E97_01783C90E8E0__INCLUDED_)
#define AFX_COMITOGGLESWITCH_H__38806ED6_1788_427F_8E97_01783C90E8E0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CComiToggleSwitch wrapper class

class CComiToggleSwitch : public CWnd
{
protected:
	DECLARE_DYNCREATE(CComiToggleSwitch)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2fea5270, 0x3610, 0x4610, { 0x8c, 0x6f, 0x8a, 0x5b, 0x15, 0xc4, 0x8e, 0x45 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	CString GetOnText();
	void SetOnText(LPCTSTR);
	CString GetOffText();
	void SetOffText(LPCTSTR);
	BOOL GetTextVisible();
	void SetTextVisible(BOOL);
	BOOL GetState();
	void SetState(BOOL);
	unsigned long GetOnColor();
	void SetOnColor(unsigned long);
	unsigned long GetOffColor();
	void SetOffColor(unsigned long);
	COleFont GetTextFont();
	void SetTextFont(LPDISPATCH);
	unsigned long GetTextOnColor();
	void SetTextOnColor(unsigned long);
	unsigned long GetTextOffColor();
	void SetTextOffColor(unsigned long);
	short GetSwitchStyle();
	void SetSwitchStyle(short);
	short GetOrientation();
	void SetOrientation(short);
	BOOL GetCommandButton();
	void SetCommandButton(BOOL);

// Operations
public:
	void EnableCtrl(short bEnable);
	short GetEnable();
	void PassKey(long nPassKey);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COMITOGGLESWITCH_H__38806ED6_1788_427F_8E97_01783C90E8E0__INCLUDED_)
